# Generated by Django 2.0.4 on 2020-06-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.IntegerField(verbose_name='0普通or1个人or2企业'),
        ),
    ]
