# Generated by Django 2.0.4 on 2020-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200609_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='suspend_status',
        ),
        migrations.AddField(
            model_name='service',
            name='is_del',
            field=models.IntegerField(default=0, verbose_name='0未删除1已删除'),
        ),
    ]
