# Generated by Django 2.0.4 on 2020-06-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_goods_tid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Comment_type',
        ),
        migrations.DeleteModel(
            name='Goods_comment_types',
        ),
        migrations.DeleteModel(
            name='QA',
        ),
    ]
