# Generated by Django 2.0.4 on 2020-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20200609_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_order',
            name='logostics_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='物流单号'),
        ),
        migrations.AlterField(
            model_name='goods_order',
            name='pays',
            field=models.IntegerField(blank=True, null=True, verbose_name='支付方式(0贡献值1记账支付)'),
        ),
    ]
