# Generated by Django 2.0.4 on 2020-06-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='公告标题')),
                ('detail', models.CharField(max_length=255, verbose_name='副标题')),
                ('details', models.CharField(max_length=255, verbose_name='详情')),
            ],
            options={
                'verbose_name': '公告信息',
                'verbose_name_plural': '公告信息',
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Assemble_type',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=0, verbose_name='0下架1上架')),
            ],
            options={
                'verbose_name': '总分类',
                'verbose_name_plural': '总分类',
                'db_table': 'assemble_type',
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='条款内容')),
            ],
            options={
                'verbose_name': '条款信息',
                'verbose_name_plural': '条款信息',
                'db_table': 'clause',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('pic', models.CharField(max_length=255, verbose_name='头像')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('title', models.CharField(max_length=255, verbose_name='副标题')),
                ('details', models.CharField(max_length=255, verbose_name='简介')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.IntegerField(default=1, verbose_name='上1下0架')),
                ('t_id', models.CharField(default=0, max_length=255, verbose_name='分类id')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Company_type',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('status', models.IntegerField(default=0, verbose_name='上架1下架0')),
            ],
            options={
                'verbose_name': '公司分类',
                'verbose_name_plural': '公司分类',
                'db_table': 'company_type',
            },
        ),
        migrations.CreateModel(
            name='Gcompany',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weixin', models.CharField(max_length=255, verbose_name='官方微信')),
                ('tep', models.CharField(max_length=30, verbose_name='客服电话')),
                ('emil', models.CharField(max_length=255, verbose_name='公司邮箱')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('details', models.CharField(max_length=255, verbose_name='平台介绍')),
            ],
            options={
                'verbose_name': '官方信息',
                'verbose_name_plural': '官方信息',
                'db_table': 'gcompany',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='帮助问题')),
                ('details', models.CharField(max_length=255, verbose_name='解决方法')),
            ],
            options={
                'verbose_name': '帮助',
                'verbose_name_plural': '帮助',
                'db_table': 'help',
            },
        ),
        migrations.CreateModel(
            name='Move_into',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=255, verbose_name='入驻人姓名')),
                ('idcard', models.CharField(max_length=255, verbose_name='身份证号')),
                ('age', models.CharField(max_length=30, verbose_name='年龄')),
                ('tep', models.CharField(max_length=30, verbose_name='电话号')),
                ('address', models.CharField(max_length=255, verbose_name='地址名称')),
                ('emil', models.CharField(max_length=255, verbose_name='邮箱')),
                ('t_id', models.IntegerField(verbose_name='类型id')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('e_id', models.CharField(default=0, max_length=255, verbose_name='审核id')),
                ('star', models.IntegerField(default=0, verbose_name='星')),
                ('drill', models.IntegerField(default=0, verbose_name='钻')),
                ('crown', models.IntegerField(default=0, verbose_name='冠')),
                ('business_scope', models.CharField(default=0, max_length=255, verbose_name='经营范围')),
                ('main_business', models.CharField(default=0, max_length=255, verbose_name='主营业务')),
                ('after_sale_service', models.CharField(default=0, max_length=255, verbose_name='售后服务')),
                ('service_info', models.CharField(default=0, max_length=255, verbose_name='服务介绍')),
            ],
            options={
                'verbose_name': '个人入驻',
                'verbose_name_plural': '个人入驻',
                'db_table': 'move_into',
            },
        ),
        migrations.CreateModel(
            name='Move_intos',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=255, verbose_name='法人姓名')),
                ('idcard', models.CharField(max_length=255, verbose_name='法人身份证号')),
                ('age', models.CharField(max_length=30, verbose_name='年龄')),
                ('tep', models.CharField(max_length=30, verbose_name='电话号')),
                ('emil', models.CharField(max_length=255, verbose_name='邮箱')),
                ('names', models.CharField(max_length=255, verbose_name='企业名称')),
                ('address', models.CharField(max_length=255, verbose_name='公司地址')),
                ('t_id', models.CharField(max_length=255, verbose_name='类型id')),
                ('pwd', models.CharField(max_length=255, verbose_name='密码')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('e_id', models.CharField(default=0, max_length=255, verbose_name='审核id')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
                ('star', models.IntegerField(default=0, verbose_name='星')),
                ('drill', models.IntegerField(default=0, verbose_name='钻')),
                ('crown', models.IntegerField(default=0, verbose_name='冠')),
                ('business_scope', models.CharField(default=0, max_length=255, verbose_name='经营范围')),
                ('main_business', models.CharField(default=0, max_length=255, verbose_name='主营业务')),
                ('after_sale_service', models.CharField(default=0, max_length=255, verbose_name='售后服务')),
                ('service_info', models.CharField(default=0, max_length=255, verbose_name='服务介绍')),
            ],
            options={
                'verbose_name': '企业入驻',
                'verbose_name_plural': '企业入驻',
                'db_table': 'move_intos',
            },
        ),
        migrations.CreateModel(
            name='Qfeedback',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=255, verbose_name='留言')),
                ('tep', models.CharField(max_length=30, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '问题反馈',
                'verbose_name_plural': '问题反馈',
                'db_table': 'qfeedback',
            },
        ),
        migrations.CreateModel(
            name='Search_take_notes',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=255, verbose_name='搜索记录')),
                ('nums', models.IntegerField(default=0, verbose_name='搜索次数')),
            ],
            options={
                'verbose_name': '用户搜索记录',
                'verbose_name_plural': '用户搜索记录',
                'db_table': 'search_take_notes',
            },
        ),
        migrations.CreateModel(
            name='User_collection',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(verbose_name='用户id')),
                ('tid', models.IntegerField(verbose_name='总分类id')),
                ('g_id', models.IntegerField(verbose_name='商品id')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'user_collection',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('star', models.IntegerField(default=0, verbose_name='星')),
                ('drill', models.IntegerField(default=0, verbose_name='钻')),
                ('crown', models.IntegerField(default=0, verbose_name='冠')),
                ('pic', models.CharField(blank=True, max_length=1000, null=True, verbose_name='头像')),
                ('tep', models.CharField(max_length=30, verbose_name='电话号码')),
                ('mmh', models.CharField(max_length=30, verbose_name='MM账号')),
                ('wxh', models.CharField(max_length=30, verbose_name='微信号')),
                ('wbh', models.CharField(max_length=30, verbose_name='微博号')),
                ('qqh', models.CharField(max_length=30, verbose_name='qq号')),
                ('type', models.IntegerField(default=0, verbose_name='0普通用户1个人入驻2企业入驻')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Users_address',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=255, verbose_name='收件人')),
                ('tep', models.CharField(max_length=30, verbose_name='电话号')),
                ('address', models.CharField(max_length=255, verbose_name='地址名称')),
                ('details', models.CharField(max_length=255, verbose_name='详情地址')),
                ('type', models.IntegerField(default=0, verbose_name='是否默认0否1是')),
            ],
            options={
                'verbose_name': '用户收获地址',
                'verbose_name_plural': '用户收获地址',
                'db_table': 'users_address',
            },
        ),
        migrations.CreateModel(
            name='Users_details',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_sum', models.IntegerField(default=0, verbose_name='贡献值')),
                ('pwd', models.CharField(max_length=255, verbose_name='支付密码')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_details', to='home.Users', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户详细信息',
                'verbose_name_plural': '用户详细信息',
                'db_table': 'users_details',
            },
        ),
    ]
